export { default as AdminDashboard} from "./AdminDashboard"
export { default as ChangePassword} from "./ChangePassword"
export { default as ForgetPassword} from "./ForgotPassword"
export { default as Login} from "./Login"
export { default as ResetPassword} from "./ResetPassword"
export { default as SuperAdminSignUp} from "./SuperAdminSignUp"
export { default as AddPerformanceScore} from "./AddPerformanceScore"